previewsEnabled: true
services:
- type: web
  name: crw
  env: node
  pullRequestPreviewsEnabled: true
  buildCommand: npm run build
  startCommand: yarn crw s
  envVars:
  - key: PORT
    value: 4016
    previewValue: 4016